// flow-typed signature: cfb963206b9f471f266ab16b4718a493
// flow-typed version: <<STUB>>/licensor_v^3.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
